/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Pikachu.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Pikachu.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={1.76}>
            <primitive object={nodes._rootJoint} />
            <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Material_160} skeleton={nodes.Object_6.skeleton} />
            <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Material_161} skeleton={nodes.Object_7.skeleton} />
            <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Material_162} skeleton={nodes.Object_8.skeleton} />
            <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Material_163} skeleton={nodes.Object_9.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Pikachu.glb')
